In [2]:
import pandas as pd

In [19]:
#Bring in CSV file which is not properly formatted but have comma separated values spread across multiple lines and first line is header
# Use on_bad_lines='skip' to skip lines with too many fields

df = pd.read_csv('MetObjects.csv', on_bad_lines='skip',low_memory=False)
print(f"Shape of dataset is  Rows X Columns : {df.shape}")
df.head(3)

Shape of dataset is  Rows X Columns : (484956, 54)

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [4]:
# Chapter 7
# Filter out missing data columns with  missing values more than 90% of data

df = df.dropna(axis = 'columns', how = "all") 
df.isna().sum()

Object Number                   0
Is Highlight                    0
Is Timeline Work                0
Is Public Domain                0
Object ID                       0
Gallery Number             435415
Department                      0
AccessionYear                3862
Object Name                  2266
Title                       28803
Culture                    276766
Period                     393813
Dynasty                    461755
Reign                      473720
Portfolio                  458442
Constituent ID             202443
Artist Role                202443
Artist Prefix              202443
Artist Display Name        202443
Artist Display Bio         204533
Artist Suffix              202491
Artist Alpha Sort          202443
Artist Nationality         202443
Artist Begin Date          202443
Artist End Date            202443
Artist Gender              378474
Artist ULAN URL            257515
Artist Wikidata URL        260754
Object Date                 13431
Object Begin Date               0
Object End Date                 0
Medium                       7215
Dimensions                  75058
Credit Line                   651
Geography Type             424997
City                       452202
State                      482335
County                     476397
Country                    408949
Region                     453456
Subregion                  462813
Locale                     469217
Locus                      477438
Excavation                 468385
River                      482864
Classification              78717
Rights and Reproduction    460427
Link Resource                   0
Object Wikidata URL        415802
Repository                      0
Tags                       292501
Tags AAT URL               292501
Tags Wikidata URL          292501
dtype: int64

In [5]:
# Fill in missing data

df = df.fillna(method='bfill')
df = df.fillna(method='ffill')
df.isna().sum()

/var/folders/cv/71w18t8n27b_81x9rhwkm1080000gq/T/ipykernel_20072/3895858002.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='bfill')
/var/folders/cv/71w18t8n27b_81x9rhwkm1080000gq/T/ipykernel_20072/3895858002.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')

Object Number              0
Is Highlight               0
Is Timeline Work           0
Is Public Domain           0
Object ID                  0
Gallery Number             0
Department                 0
AccessionYear              0
Object Name                0
Title                      0
Culture                    0
Period                     0
Dynasty                    0
Reign                      0
Portfolio                  0
Constituent ID             0
Artist Role                0
Artist Prefix              0
Artist Display Name        0
Artist Display Bio         0
Artist Suffix              0
Artist Alpha Sort          0
Artist Nationality         0
Artist Begin Date          0
Artist End Date            0
Artist Gender              0
Artist ULAN URL            0
Artist Wikidata URL        0
Object Date                0
Object Begin Date          0
Object End Date            0
Medium                     0
Dimensions                 0
Credit Line                0
Geography Type             0
City                       0
State                      0
County                     0
Country                    0
Region                     0
Subregion                  0
Locale                     0
Locus                      0
Excavation                 0
River                      0
Classification             0
Rights and Reproduction    0
Link Resource              0
Object Wikidata URL        0
Repository                 0
Tags                       0
Tags AAT URL               0
Tags Wikidata URL          0
dtype: int64

In [6]:
# Chapter 8

# Create hierarchical index
df_index = df.set_index(['Object Number', 'Object ID'])
df_index.index

MultiIndex([(   '1979.486.1',      1),
            (   '1980.264.5',      2),
            (     '67.265.9',      3),
            (    '67.265.10',      4),
            (    '67.265.11',      5),
            (    '67.265.12',      6),
            (    '67.265.13',      7),
            (    '67.265.14',      8),
            (    '67.265.15',      9),
            (   '1979.486.3',     10),
            ...
            ('2022.459.13.5', 900494),
            ('2022.459.13.6', 900495),
            ('2022.459.13.7', 900496),
            ('2022.459.13.8', 900497),
            (     '54.646.1', 900602),
            (   '55.621.134', 900605),
            (     '1977.646', 900606),
            (      '33.40.1', 900633),
            (    '170.1 C42', 900717),
            (    '17.3.3457', 900748)],
           names=['Object Number', 'Object ID'], length=484956)

In [7]:

# Pivot the data

# As there are 400K rows, i selected just 2000 rows to pivot post removing duplicates from index. 

df_subset = df.drop_duplicates(subset=['State']).head(2000)
df_pivot = df_subset.pivot(index='State', columns='Region', values='City') # pivoting on Culture and Tags
print(df_pivot.isna().sum())
df_pivot.head()

Region
Adanse traditional area     107
Bakhtiari tribe             107
Barotseland                 107
Berber                      107
Bohemia                      98
Caucasus                    106
Fayum Entrance Area         107
Flanders                    107
Mato Grosso                 107
Memphite Region             105
Mid-Atlantic                106
Mid-Atlantic                104
Midwest                     100
New England                  41
South United States         107
Upper Egypt, Thebes         105
Yorkshire and the Humber    107
dtype: int64

Region,Adanse traditional area,Bakhtiari tribe,Barotseland,Berber,Bohemia,Caucasus,Fayum Entrance Area,Flanders,Mato Grosso,Memphite Region,Mid-Atlantic,Mid-Atlantic,Midwest,New England,South United States,"Upper Egypt, Thebes",Yorkshire and the Humber
State,,,,,,,,,,,,,,,,,
Alamance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pittsburgh,NaN,NaN,NaN
Alamance County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,NaN,NaN,NaN,NaN,NaN
Albany County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Newport,NaN,NaN,NaN
Bergen County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,NaN,NaN,NaN
Bergen|Rockland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,NaN,NaN,NaN

In [8]:
# Chapter 10

# Grouping with Functions
dept_first_letter_counts = df.groupby(df['Department'])['Object ID'].count()
dept_first_letter_counts

Department
Ancient Near Eastern Art                       6223
Arms and Armor                                13623
Arts of Africa, Oceania, and the Americas     12367
Asian Art                                     37000
Costume Institute                             31652
Drawings and Prints                          172630
Egyptian Art                                  27969
European Paintings                             2626
European Sculpture and Decorative Arts        43051
Greek and Roman Art                           33726
Islamic Art                                   15573
Medieval Art                                   7142
Modern and Contemporary Art                   14696
Musical Instruments                            5227
Photographs                                   37459
Robert Lehman Collection                       2586
The American Wing                             18532
The Cloisters                                  2340
The Libraries                                   534
Name: Object ID, dtype: int64

In [9]:
# Cross Tabs
dept_cross_tab = pd.crosstab(df['Department'], df['Culture'], margins=True)
dept_cross_tab

Culture,"\r\nChugach, Native American","""Peking"" work",Abau people,Abelam people,Abenaki (?),"Abor, Burmese",Abron,Acehnese,Achaemenid,Achaemenid (?),...,probably northern European (probably German),probably provincial British,probably south Lowlands; possibly Bohemia or Saxony,"saddle plate, Chinese or Tibetan; harness fittings, Tibetan",southern German or Tyrolese; cranequin probably German or Swiss,"spearhead, Chinese or Mongolian; case, Tibetan","staff, Indian; banner, Mahdist Sudanese",unknown,unknown (Italian style),All
Department,,,,,,,,,,,,,,,,,,,,,
Ancient Near Eastern Art,0,0,0,0,0,0,0,0,179,6,...,0,0,0,0,0,0,0,0,0,6223
Arms and Armor,0,1,0,0,0,1,0,0,0,0,...,0,0,0,1,1,1,1,0,0,13623
"Arts of Africa, Oceania, and the Americas",0,0,1,41,1,0,1,2,0,0,...,0,0,0,0,0,0,0,0,0,12367
Asian Art,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,37000
Costume Institute,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,31652
Drawings and Prints,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,172630
Egyptian Art,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,27969
European Paintings,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2626
European Sculpture and Decorative Arts,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,43051
Greek and Roman Art,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,33726
Islamic Art,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15573
Medieval Art,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7142
Modern and Contemporary Art,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,14696
Musical Instruments,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5227
Photographs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,37459
Robert Lehman Collection,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,1,5,2586
The American Wing,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,18532
The Cloisters,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2340
The Libraries,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,534
All,1,1,1,41,1,1,1,2,179,6,...,1,1,1,1,1,1,1,1,5,484956

In [13]:
# Chapter 11
# Convert between string and date time

# Convert 'AccessionYear' from string to datetime. At some places it year is in format YYYY-MM-DD and at some places it is just YYYY
# We will convert it to datetime and then back to string with just year and to handle the errors arising due to different formats
# we will use errors='coerce' to convert invalid parsing to NaT (Not a Time)
df['AccessionYear_dt'] = pd.to_datetime(df['AccessionYear'], format="%Y", errors='coerce')

# Convert datetime back to string (year only)
df['AccessionYear_str'] = df['AccessionYear_dt'].dt.strftime('%Y-%m-%d')

df.head()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Repository,Tags,Tags AAT URL,Tags Wikidata URL,AccessionYear_dt,AccessionYear_str
0,1979.486.1,False,False,False,1,774,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search/1,https://www.wikidata.org/wiki/Q116250677,"Metropolitan Museum of Art, New York, NY",Birds|Coins,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,1979-01-01,1979-01-01
1,1980.264.5,False,False,False,2,774,The American Wing,1980,Coin,Ten-dollar Liberty Head Coin,...,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search/2,https://www.wikidata.org/wiki/Q116250677,"Metropolitan Museum of Art, New York, NY",Birds|Coins,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,1980-01-01,1980-01-01
2,67.265.9,False,False,False,3,774,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search/3,https://www.wikidata.org/wiki/Q116250677,"Metropolitan Museum of Art, New York, NY",Birds|Coins,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,1967-01-01,1967-01-01
3,67.265.10,False,False,False,4,774,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search/4,https://www.wikidata.org/wiki/Q116250677,"Metropolitan Museum of Art, New York, NY",Birds|Coins,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,1967-01-01,1967-01-01
4,67.265.11,False,False,False,5,774,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search/5,https://www.wikidata.org/wiki/Q116250677,"Metropolitan Museum of Art, New York, NY",Birds|Coins,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,1967-01-01,1967-01-01

In [17]:
# Generate date range
df_subset['date_range'] = pd.date_range('2020-01-01', periods=108, freq='D')
df_subset.head()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Repository,Tags,Tags AAT URL,Tags Wikidata URL,date_range
0,1979.486.1,False,False,False,1,774,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,Atrato River,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search/1,https://www.wikidata.org/wiki/Q116250677,"Metropolitan Museum of Art, New York, NY",Birds|Coins,http://vocab.getty.edu/page/aat/300266506|http...,https://www.wikidata.org/wiki/Q5113|https://ww...,2020-01-01
305,40.184.2,False,False,True,351,704,The American Wing,1940,Basin,Basin,...,Atrato River,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search...,https://www.wikidata.org/wiki/Q116373471,"Metropolitan Museum of Art, New York, NY",Doors,http://vocab.getty.edu/page/aat/300002803,https://www.wikidata.org/wiki/Q36794,2020-01-02
364,13.197.2,False,False,True,419,704,The American Wing,1913,Beaker,Beaker,...,Atrato River,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search...,https://www.wikidata.org/wiki/Q116373396,"Metropolitan Museum of Art, New York, NY",Flowers,http://vocab.getty.edu/page/aat/300132399,https://www.wikidata.org/wiki/Q506,2020-01-03
381,10.125.335,False,False,True,436,774,The American Wing,1910,Folding bedstead,Folding Bedstead,...,Atrato River,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search...,https://www.wikidata.org/wiki/Q116373374,"Metropolitan Museum of Art, New York, NY",Flowers,http://vocab.getty.edu/page/aat/300132399,https://www.wikidata.org/wiki/Q506,2020-01-04
423,83.2.234,False,False,True,482,774,The American Wing,1883,Painting,Portrait of Benjamin Franklin,...,Atrato River,Metalwork-Brass,"© 2023 Artists Rights Society (ARS), New York",http://www.metmuseum.org/art/collection/search...,https://www.wikidata.org/wiki/Q79023693,"Metropolitan Museum of Art, New York, NY",Benjamin Franklin|Men|Portraits,http://vocab.getty.edu/page/ulan/500331804|htt...,https://www.wikidata.org/wiki/Q34969|https://w...,2020-01-05